name: behaviour_tree
version: 0.9.1
author: Will Squire <will.mj.squire@googlemail.com>
description: A behaviour tree library for Dart.
homepage: https://twitter.com/WillSquire
dev_dependencies:
  unittest: any
