name: behaviour_tree
description: >
  A library useful for applications or for sharing on pub.dartlang.org.
version: 0.8.0
author: Will Squire <will.mj.squire@googlemail.com>
homepage: https://twitter.com/WillSquire
#dependencies:
#  lib_name: any
dev_dependencies:
  unittest: any
